############################################################################
# vendor/sg2000/boards/sg2000/milkv_duos/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(TOPDIR)/Make.defs

RCSRCS = etc/init.d/rc.sysinit etc/init.d/rcS

CSRCS = sg2000_appinit.c gc2083_test.c

include $(TOPDIR)/boards/Board.mk
